config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount Attachinary::Engine => "/attachinary"

  post 'boats/:id/bookings', to: 'bookings#create', as: 'boat_bookings'
  get 'bookings', to: 'bookings#index'
  get 'boats/:id/bookings/confirm', to: 'bookings#confirm', as: 'boats_booking_confirm'
  get 'boats/:id', to: 'boats#show', as: 'boat'
  get 'boats', to: 'boats#results'
  get 'profile', to: 'users#profile'

  namespace :host do
    get 'bookings', to: 'bookings#index'
    get 'bookings/:id/accept', to: 'bookings#accept', as: 'booking_approve'
    get 'bookings/:id/reject', to: 'bookings#reject', as: 'booking_reject'
    get 'boats', to: 'boats#index'
    get 'boats/new', to: 'boats#new'
    post 'boats', to: 'boats#create'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Produced by AirBnBoats Ltd 2017 <i class="fa fa-copyright" aria-hidden="true"></i>All Rights Reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= 'navbar-wagon-fixed' if @fix_navbar %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if current_page?(boats_path) %>
      <div class="navbar-wagon">
        <%= render "shared/searchbar" %>
      </div>
    <% end %>
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Trips", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="dropdown">
        <%= link_to "My Boats", host_boats_path, class: "navbar-wagon-item navbar-wagon-link", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
             <%= link_to host_boats_path do %>
                <i class="fa fa-list-ul"></i> <%= t(".profile", default: " My boats") %>
              <% end %>
            </li>
            <li>
             <%= link_to host_boats_new_path do %>
                <i class="fa fa-plus"></i> <%= t(".profile", default: "  Add boat") %>
              <% end %>
            </li>
            <li>
             <%= link_to host_bookings_path do %>
                <i class="fa fa-ship"></i> <%= t(".profile", default: "  My Bookings") %>
              <% end %>
            </li>
       </ul>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% elsif current_user.photo %>
            <%= cl_image_tag current_user.photo.path, width: 400, height: 300, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
            <%= cl_image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPH5L6M6fkEYaNM5mYLZqufGiIXJP9hnM91L-cekfMyR6Juv-O', width: 400, height: 300, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>


          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t(".account", default: "My account") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: " Log-out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li><%= link_to bookings_path do %>
          <div><i class="fa fa-binoculars" aria-hidden="true"></i> My Trips</div>
            <% end %>
        </li>
        <li><%= link_to host_boats_path do %>
          <div><i class="fa fa-ship" aria-hidden="true"></i> My Boats</div>
            <% end %>
        </li>
        <li><%= link_to profile_path do %>
          <div><i class="fa fa-user"></i> My Profile</div>
            <% end %>
        </li>
        <li><%= link_to edit_user_registration_path do %>
          <div><i class="fa fa-cog"></i> My Account</div>
            <% end %>
        </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <div><i class="fa fa-sign-out"></i> Log Out</div>
            <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<form role="form" action="boats" method="get">
  <div class="col-md-4">
    <div class="form-group">
      <label class="sr-only" for="locationTextField">Location</label>
      <input type="search" class="form-control" id="locationTextField"  name="location" placeholder="Where ?">
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group">
      <label class="sr-only" for="chkin">Check in</label>
      <div class="input-group">
        <input type="text" class="form-control" id="chkin" name="chkin" placeholder="Check in">
        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkin"></i></span>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group">
      <label class="sr-only" for="chkout">Check out</label>
      <div class="input-group">
        <input type="text" class="form-control" id="chkout"  name="chkout" placeholder="Check out">
        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkout"></i></span>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="form-group">
      <label class="sr-only" for="guest">Guest</label>
      <select id="guest" name="guests" class="form-control">
          <option value="1">1 Guest</option>
          <option value="2">2 Guests</option>
          <option value="3">3 Guests</option>
          <option value="4">4 Guests</option>
          <option value="5">5 Guests</option>
          <option value="6">6 Guests</option>
          <option value="7">7 Guests</option>
          <option value="8">8 Guests</option>
          <option value="9">9 Guests</option>
          <option value="10">10+ Guests</option>
      </select>
    </div>
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-default btn-block <%= current_page?(root_path) ? "btn-primary" : "btn-default"  %>">Search</button>
  </div>
</form>