config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount Attachinary::Engine => "/attachinary"

  post 'boats/:id/bookings', to: 'bookings#create', as: 'boat_bookings'
  get 'bookings', to: 'bookings#index'
  get 'boats/:id/bookings/confirm', to: 'bookings#confirm', as: 'boats_booking_confirm'
  get 'boats/:id', to: 'boats#show', as: 'boat'
  get 'boats', to: 'boats#results'
  get 'profile', to: 'users#profile'

  namespace :host do
    get 'bookings', to: 'bookings#index'
    get 'bookings/:id/accept', to: 'bookings#accept', as: 'booking_approve'
    get 'bookings/:id/reject', to: 'bookings#reject', as: 'booking_reject'
    get 'boats', to: 'boats#index'
    get 'boats/new', to: 'boats#new'
    post 'boats', to: 'boats#create'
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
  has_many :booking_slots

  validates :status, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :boat_id, presence: true
  validates :user_id, presence: true
  validates :rating, inclusion: { in: 0..5 }

  def default_values
    self.rating ||= 0
    self.status ||= 'pending' # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
  end

  def confirm
    #First, we want to put the booking dates into a range (15ofjuly..18ofjuly).
    @booking= Booking.new
    @booking.user = current_user
    @booking.start_date = params[:chkin]
    @booking.end_date = params[:chkout]
    desired = @booking.start_date..@booking.end_date

    #We want to have an array of all the booking date ranges already existing for this boat.
    @booking.boat_id = params[:id]
    @boat = Boat.find(params[:id])
    booked = []
    @boat.bookings.each do |booking|
      booked << (booking.start_date..booking.end_date)
    end

    #Third, we want to compare our new booking date range with all the one existing and accept or refuse booking accordingly.
    booked.each do|booker|

      if booker.overlaps?(desired)
          redirect_to boat_path(@boat), notice: 'Dates are overlapping' and return
      end
    end
  end

  def create
    @booking = Booking.new
    @booking.start_date = params[:booking][:start_date]
    @booking.end_date = params[:booking][:end_date]
    @booking.user = current_user
    @booking.boat_id = params[:id]
    @booking.default_values
    @booking.intro = params[:booking][:intro]

    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:chkin, :chkout)
  end
end

app/controllers/host/boats_controller.rb
class Host::BoatsController < ApplicationController
  def index
    @host = current_user
    @host_boats = @host.boats
  end

  def new
    @boat = Boat.new
    @host = current_user
  end

  def create
    @host = current_user
    @boat = Boat.new(boat_params)
    @boat.user = @host
    if @boat.save
      redirect_to host_boats_path
    else
      render :new
    end
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :category, :subcategory, :skipper, :description, :num_of_beds, :num_of_bath, :location, :capacity, :price , photos: [])
  end
end

app/controllers/host/bookings_controller.rb
class Host::BookingsController < ApplicationController
  def index
    if current_user
      @ownerbookings = current_user.owner_bookings
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    make_booking_availability_slots(@booking)
    redirect_to host_bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    remove_booking_availability_slots(@booking)
    redirect_to host_bookings_path
  end

  private

  def make_booking_availability_slots(booking)
    start_d = booking.start_date
    end_d = booking.end_date
    count = 0
    (start_d..end_d).each do |d|
      if AvailabilitySlot.exists?(boat_id: booking.boat_id, date: d)
        count += 1
      end
    end
    if count == (start_d..end_d).count
      (start_d..end_d).each do |d|
        availslot = AvailabilitySlot.where(boat_id: booking.boat_id, date: d).take
        BookingSlot.create(availability_slot_id: availslot.id, booking_id: booking.id)
      end
      booking.update(:status => 'approved')
    end
  end

  def remove_booking_availability_slots(booking)
    if booking.status = "approved"
      booking.booking_slots.each do |slot|
        slot.destroy
      end
      booking.update(:status => 'rejected')
    end
  end
end

app/views/host/bookings/accept.html.erb
<h1>Host::Bookings#accept</h1>
<p>Find me in app/views/host/bookings/accept.html.erb</p>

app/views/host/bookings/index.html.erb
<div class="inbox-container">
  <h1>Your bookings</h1>
  <div class="tabs">
    <a href="#" id="pend" class="tab active">Pending</a>
    <a href="#" id="appr" class="tab">Approved</a>
    <a href="#" id="reje" class="tab">Rejected</a>
  </div>
<div class="inbox-border">
  <ul class="inbox hidden-inbox" id="approved">
  <% @ownerbookings.where(status: "approved").each do |booking| %>
    <li class="message">
      <% if booking.user.photo %>
        <%= cl_image_tag booking.user.photo.path, class: "message-avatar" %>
        <% else %>
        <%= cl_image_tag 'https://res.cloudinary.com/wagon/image/upload/c_fill,h_100,w_100/v1473854796/eicc6dsuwpw1ieyhhxxa.jpg', width: 400, height: 300, crop: :thumb, gravity: :face, class: "message-avatar" %>
      <% end %>
      <div class="message-meta">
        <p class="name"><%= booking.user.firstname %> <%= booking.user.lastname %></p>
        <p><%= booking.created_at.strftime("%d-%b-%Y") %></p>
      </div>
      <div class="message-payload">
        <p class="message-title"><strong>Booking Request <%= booking.start_date.strftime("%d-%b-%Y") %> to <%= booking.end_date.strftime("%d-%b-%Y") %> </strong></p>
        <p><%= booking.intro %></p>
      </div>
      <div class="message-reject">
        <%= link_to host_booking_reject_path(booking) do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="message-status">
        <p class="<%= booking.status %>"><%= booking.status %></p>
        <p class="price">€ <%= booking.boat.price * (booking.end_date - booking.start_date).to_i %></p>
      </div>
    </li>
  <% end %>
  </ul>
  <ul class="inbox hidden-inbox" id="rejected">
  <% @ownerbookings.where(status: "rejected").each do |booking| %>
    <li class="message">
      <% if booking.user.photo %>
        <%= cl_image_tag booking.user.photo.path, class: "message-avatar" %>
        <% else %>
        <%= cl_image_tag 'https://res.cloudinary.com/wagon/image/upload/c_fill,h_100,w_100/v1473854796/eicc6dsuwpw1ieyhhxxa.jpg', width: 400, height: 300, crop: :thumb, gravity: :face, class: "message-avatar" %>
      <% end %>
      <div class="message-meta">
        <p class="name"><%= booking.user.firstname %> <%= booking.user.lastname %></p>
        <p><%= booking.created_at.strftime("%d-%b-%Y") %></p>
      </div>
      <div class="message-payload">
        <p class="message-title"><strong>Booking Request <%= booking.start_date.strftime("%d-%b-%Y") %> to <%= booking.end_date.strftime("%d-%b-%Y") %> </strong></p>
        <p><%= booking.intro %></p>
      </div>
      <div class="message-approve">
        <%= link_to host_booking_approve_path(booking) do %>
          <i class="fa fa-check" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="message-status">
        <p class="<%= booking.status %>"><%= booking.status %></p>
        <p class="price">€ <%= booking.boat.price * (booking.end_date - booking.start_date).to_i %></p>
      </div>
    </li>
  <% end %>
  </ul>
  <ul class="inbox" id="pending">
  <% @ownerbookings.where(status: "pending").each do |booking| %>
    <li class="message">
      <% if booking.user.photo %>
        <%= cl_image_tag booking.user.photo.path, class: "message-avatar" %>
        <% else %>
        <%= cl_image_tag 'https://res.cloudinary.com/wagon/image/upload/c_fill,h_100,w_100/v1473854796/eicc6dsuwpw1ieyhhxxa.jpg', width: 400, height: 300, crop: :thumb, gravity: :face, class: "message-avatar" %>
      <% end %>
      <div class="message-meta">
        <p class="name"><%= booking.user.firstname %> <%= booking.user.lastname %></p>
        <p><%= booking.created_at.strftime("%d-%b-%Y") %></p>
      </div>
      <div class="message-payload">
        <p class="message-title"><strong>Booking Request <%= booking.start_date.strftime("%d-%b-%Y") %> to <%= booking.end_date.strftime("%d-%b-%Y") %> </strong></p>
        <p><%= booking.intro %></p>
      </div>
      <div class="message-approve">
        <%= link_to host_booking_approve_path(booking) do %>
          <i class="fa fa-check" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="message-reject">
        <%= link_to host_booking_reject_path(booking) do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="message-status">
        <p class="<%= booking.status %>"><%= booking.status %></p>
        <p class="price">€ <%= booking.boat.price * (booking.end_date - booking.start_date).to_i %></p>
      </div>
    </li>
  <% end %>
  </ul>
</div>
</div>

<%= content_for :after_js do %>
<script>
  $(document).ready(function(){
    $('.inbox').hide();
    $('#pending').show();
    $('.tab').removeClass('active')
    $('#pend').addClass('active');

    $('#pend').click(function(){
      $('.tab').removeClass('active');
      $('#pend').addClass('active');
      $('.inbox').hide();
      $('#pending').show();
    });

    $('#appr').click(function(){
      console.log("ddd")
      $('.tab').removeClass('active');
      $('#appr').addClass('active');
      $('.inbox').hide();
      $('#approved').show();
    });

    $('#reje').click(function(){
      $('.tab').removeClass('active');
      $('#reje').addClass('active');
      $('.inbox').hide();
      $('#rejected').show();
    });
  });
</script>
<% end %>

app/views/host/bookings/reject.html.erb
<h1>Host::Bookings#reject</h1>
<p>Find me in app/views/host/bookings/reject.html.erb</p>