config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  mount Attachinary::Engine => "/attachinary"

  post 'boats/:id/bookings', to: 'bookings#create', as: 'boat_bookings'
  get 'bookings', to: 'bookings#index'
  get 'boats/:id/bookings/confirm', to: 'bookings#confirm', as: 'boats_booking_confirm'
  get 'boats/:id', to: 'boats#show', as: 'boat'
  get 'boats', to: 'boats#results'
  get 'profile', to: 'users#profile'

  namespace :host do
    get 'bookings', to: 'bookings#index'
    get 'bookings/:id/accept', to: 'bookings#accept', as: 'booking_approve'
    get 'bookings/:id/reject', to: 'bookings#reject', as: 'booking_reject'
    get 'boats', to: 'boats#index'
    get 'boats/new', to: 'boats#new'
    post 'boats', to: 'boats#create'
  end
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :availability_slots
  has_many :bookings
  has_many :booking_slots, through: :bookings

  validates :name, presence: true, length: { maximum: 30 }
  validates :category, presence: true, inclusion: { in: ["Motor", "Sailing"] }
  validates :subcategory, presence: true, inclusion: { in: ["Rigid", "Semi-rigid", "Dinghy", "Catamaran", "Keelboat"] }
  validates :skipper, inclusion: { in: [true, false] }
  validates :description, presence: true
  validates :num_of_beds, presence: true, inclusion: { in: 0..15 }
  validates :num_of_bath, presence: true, inclusion: { in: 0..15 }
  validates :location, presence: true
  validates :capacity, presence: true, inclusion: { in: 0..1000 }
  validates :price, presence: true, inclusion: { in: 0..10000 }
  validates :user_id, presence: true

  has_attachments :photos, maximum: 5

  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def show
    @boat = Boat.find(params[:id])
    dates = []
    @boat.booking_slots.each do |booking_slot|
      dates << booking_slot.availability_slot.date.strftime("%d-%m-%Y")
    end
    @blocked_dates = dates
  end

  def results
    @fix_navbar = true

    if params[:location].blank?
      @boats = Boat.all
    else
      @boats = Boat.near(params[:location], 30).where("capacity >= ?", params[:guests])
    end

    @boats2 = Boat.near(params[:location], 30).where("capacity >= ?", params[:guests]).where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@boats) do |boat, marker|
      marker.lat boat.latitude
      marker.lng boat.longitude
      # marker.infowindow render_to_string(partial: "/boats/map_box", locals: { boat: boat })
    end
  end

  private

  def boat_params
    params.require(:boat).permit(photos: [])
  end

end

app/controllers/host/boats_controller.rb
class Host::BoatsController < ApplicationController
  def index
    @host = current_user
    @host_boats = @host.boats
  end

  def new
    @boat = Boat.new
    @host = current_user
  end

  def create
    @host = current_user
    @boat = Boat.new(boat_params)
    @boat.user = @host
    if @boat.save
      redirect_to host_boats_path
    else
      render :new
    end
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :category, :subcategory, :skipper, :description, :num_of_beds, :num_of_bath, :location, :capacity, :price , photos: [])
  end
end

app/views/boats/_card.html.erb
<%= link_to boat_path(partial_boat) do %>
  <div class="card">
    <%= cl_image_tag(partial_boat.photos.first.path, class: "card-image", alt: partial_boat.name) %>
    <div class="card-details">
      <div class="title"> <h5> <%= partial_boat.name %> </h5></div>
      <div class="description"><h6> <%= partial_boat.category%> - for <%= partial_boat.capacity%> people </h6> </div>
    </div>
  </div>
<% end %>

app/views/boats/_results.html.erb
<div class="col-xs-12 row">
  <% @boats.each do |boat| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <%= render "card", partial_boat: boat %>
    </div>
  <% end %>
</div>

app/views/boats/results.html.erb
<div class="row" id="results-wrapper">
  <div class="col-xs-8 results-display" id="results-column">
    <%= render "results" %>
  </div>

  <div class="col-xs-4 results-display" id="results-map">

    <div id="map" ></div>
  </div>
</div>




  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}
" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(0);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/boats/show.html.erb
<% content_for :addtional_class, "white-background" %>

<div class="row intro">
  <div class="col-xs-3 element hola">
    <div class="hello">
    <div id="photo">
      <% if @boat.user.photo? %>
      <%=cl_image_tag @boat.user.photo.path, id:"owner-picture" %>
      <% else %>
         <img src="http://www.dickson-constant.com/medias/images/catalogue/api/m654-grey-680.jpg" id="owner-picture" alt="">
      <% end %>
    </div>
    <div id="identity">
      <p><%= @boat.user.firstname %> <%= @boat.user.lastname %></p>
    </div>
  </div>
  </div>
  <div class="col-xs-6 hola">
    <div><h1><strong><%= @boat.name %></strong></h1></div>
  </div>
    <div class="col-xs-3 hola">
    <% if  @boat.num_of_beds < 6 %>
      <div><p style="font-size: 40px; color: #ffd700"><%= "*" * @boat.num_of_beds %></p></div>
      <% elsif @boat.num_of_beds > 6 %>
        <p style="font-size: 40px; color: #ffd700"> <%= "*" * 5 %></p>
      <% else %>
        <p style="font-size: 20px; color: #33658A; border: 2px solid #33658A; padding: 10px"> No rating yet</p>
      <% end %>
    </div>
</div>

<hr />
<div class="container">


<div class="row">
 <div id="pictures">
  <% @boat.photos.each do |photo| %>
  <%= link_to cl_image_path(photo.path, width: 700, height: 500, crop: :fill), class:"swipebox" do %>
      <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
    <% end %>
  <% end %>
  </div>
</div>

  <div class="row content">
    <div class="col-xs-8 details">
      <p id="greeting">Welcome on board of <%= @boat.name %> !</p>
      <p>Category: <%= @boat.category %></p>
      <hr/>
      <p>Subcategory: <%= @boat.subcategory %></p>
       <hr/>
      <p>Number of beds: <%= @boat.num_of_beds %></p>
       <hr/>
      <p>Number of bath: <%= @boat.num_of_bath %></p>
       <hr/>
      <p>Total capacity: <%= @boat.capacity %></p>
       <hr/>
      <p>Boat description: <%= @boat.description %></p>
       <p>Boat description: <%= @boat.description %></p>
        <p>Boat description: <%= @boat.description %></p>
         <p>Boat description: <%= @boat.description %></p>
          <p>Boat description: <%= @boat.description %></p>
           <hr/>
    </div>



    <% if user_signed_in? %>
    <div class="col-xs-4" id="booking">
      <div class="row space">
        <div class="col-md-6">
          <p id="price">from <strong><%= @boat.price %></strong> euros/day </p>
        </div>
      </div>
      <form role="form" action= "/boats/<%= @boat.id %>/bookings/confirm" method="get">
        <div class="row space">
          <div class="col-md-6">
            <div class="form-group">
              <label class="sr-only" for="chkin">Check in</label>
            <div class="input-group">
              <input type="text" class="form-control" id="chkin" name="chkin" placeholder="Check in">
              <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkin"></i></span>
            </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="sr-only" for="chkout">Check out</label>
            <div class="input-group">
              <input type="text" class="form-control" id="chkout"  name="chkout" placeholder="Check out">
              <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" id="glyph-chkout"></i></span>
             </div>
            </div>
           </div>
        </div>
           <div class="row space">
             <div class="col-md-6 col-md-offset-3">
              <button type="submit" class="btn btn-primary btn-block <%= current_page?(root_path) ? "btn-primary" : "btn-default"  %>">Book now</button>
             </div>
           </div>
      </form>
   </div>

  <%else %>
  <div class="col-xs-4" id="booking-unavailalble">
    <h3>Booking unavailable</h3>
    <p>In order to make a booking for <strong><%= @boat.name %></strong> please either: </p>

    <p><%= link_to "Log in", new_user_session_path, {class: "btn btn-primary"}%>    or    <%= link_to "Sign up", new_user_registration_path, {class: "btn btn-primary"}%></p>
    </div>

  <% end %>

  </div>
</div>

<%= content_for :after_js do %>
  <script>
  $(document).ready(function(){
    $( '.swipebox' ).swipebox();
    var disableddates = <%=  raw @blocked_dates %>
    checkin = $("#chkin").datepicker({
      format : 'dd/mm/yyyy',
      orientation: "bottom",
      autoclose: true,
      todayHighlight: true,
    });
    checkout = $("#chkout").datepicker({
      format : 'dd/mm/yyyy',
      orientation: "bottom",
      autoclose: true,
      todayHighlight: true,
    });
    checkin.data('datepicker').setDatesDisabled(disableddates);
    checkout.data('datepicker').setDatesDisabled(disableddates);
  });
  </script>
<% end %>

<!-- <script src="lib/jquery-2.0.3.js"></script>
<script src="src/js/jquery.swipebox.js"></script> -->